name: 'Composite Upload-Artifact'
description: 'Use different version of upload-artifact based on input'
inputs:
  hosted:  
    description: 'Is running on hosted'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: upload-artifacts v4
      if: ${{ inputs.hosted == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: .github/
        if-no-files-found: ignore
    
    - name: upload-artifacts v3
      if: ${{ inputs.hosted != 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: .github/
        if-no-files-found: ignore
